all:
	cd invertdistro; make;
	cd fit; make;
	cd fast_pow; make;
	cd memory; make;
	cd options; make;
	cd random; make;
	cd rk; make;

clean:
	cd invertdistro; make clean;
	cd fit; make clean;
	cd fast_pow; make clean;
	cd memory; make clean;
	cd options; make clean;
	cd random; make clean;
	cd rk; make clean;
